services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:latest
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx2G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_PASSWORD}
      
      - LAVALINK_SERVER_SOURCES_YOUTUBE=false
      - LAVALINK_PLUGINS_0_REPOSITORY=https://maven.lavalink.dev/releases
      - LAVALINK_PLUGINS_0_DEPENDENCY=dev.lavalink.youtube:youtube-plugin:1.14.0
      
      - LAVALINK_PLUGINS_1_REPOSITORY=https://maven.lavalink.dev/releases
      - LAVALINK_PLUGINS_1_DEPENDENCY=com.github.topi314.lavasrc:lavasrc-plugin:4.3.0
      - PLUGINS_LAVASRC_PROVIDERS_SPOTIFY=true
      - PLUGINS_LAVASRC_SPOTIFY_CLIENTID=${SPOTIFY_CLIENT_ID}
      - PLUGINS_LAVASRC_SPOTIFY_CLIENTSECRET=${SPOTIFY_CLIENT_SECRET}
      
      - PLUGINS_LAVASRC_SOURCES_SPOTIFY=true
      - PLUGINS_LAVASRC_SPOTIFY_COUNTRYCODE=US
    ports:
      - "2333:2333"
    networks:
      - bot_network

  discord_music_bot:
    build: .
    container_name: discord_music_bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - lavalink
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
