services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:latest
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx1G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
      - LAVALINK_SERVER_SOURCES_YOUTUBE=false
      - LAVALINK_PLUGINS_0_REPOSITORY=https://maven.lavalink.dev/releases
      - LAVALINK_PLUGINS_0_DEPENDENCY=dev.lavalink.youtube:youtube-plugin:1.14.0
    ports:
      - "2333:2333"

  bot:
    build: .
    container_name: discord_music_bot
    restart: unless-stopped
    depends_on:
      - lavalink
    env_file:
      - .env
